version: '3'

services:
  website-monitor:
    build: .
    container_name: five-tours-monitor
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./:/app
    environment:
      - TZ=UTC

  otp-sender:
    build: ./otp_sender
    container_name: otp-sender
    restart: unless-stopped
    volumes:
      - ./otp_sender:/app
    environment:
      - TZ=UTC
